backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Skills"
    name: "skill"
    folder: "markdown/skills"
    identifier_field: skillName
    create: true
    editor:
      preview: true
    fields:
      - { label: "Skill Name", name: "skillName", widget: "string" }
      - {
          label: "Percentage",
          name: "percentage",
          widget: "number",
          valueType: "int",
          min: 0,
          max: 100,
        }
  - label: "Timeline Items"
    name: "timelineItem"
    folder: "markdown/timelineItems"
    identifier_field: timelineTitle
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "timelineTitle", widget: "string" }
      - { label: "Description", name: "timelineDescription", widget: "string" }
      - {
          label: "Year",
          name: "year",
          widget: "date",
          default: "",
          format: "YYYY",
        }
  - label: "Videos"
    name: "video"
    folder: "markdown/videos"
    identifier_field: videoTitle
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "videoTitle", widget: "string" }
      - label: "Thumbnail"
        name: "thumbnail"
        widget: "image"
        media_library:
          config:
            multiple: false
      - { label: "Youtube URL", name: "youtubeUrl", widget: "string" }
